# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a31560dd14ab9431aba4df78fcdbe12795618c0acd6f480557769b1197c6455120e2b96739457982b968e305880cc9ae16393747ad9304a6fdc620c0a5b2f076

test:
  secret_key_base: d70bf47aa48cd43003add3848b4cbd6ea8da304fdb9ddc5dc4db35a93f8144ed4dc51f88cd68f3af8377fa9657e83636a3cb37bc9b291282e499a2ed5d6d785b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
